### ISSUE TITLE
[UI] Play time randomly flickering

### ISSUE THREAD

**Issue by Juesto** [kritzikratzi/Oscilloscope#25]
it's me or there's still some settings to polish yet?
Yes, as the title says, the play time bar swaps from the current position to the beginning and returns to the same position, it happens fast.
Also when using microphone mode you can still play/pause uselessly(?) and the button gets somewhat stuck (Didn't fully test this)
Exact values are not shown in the app but it's almost impossible to get "perfect" values when using the slider.

**Comment by kritzikratzi** [comment]
one bug per bug report please :) 

yes, there's always things to be polished. but someone has to do it. 

undocumented blur setting: nope, it's and old setting and not in use anymore. 
title bar swaps: yep, true. i'll make this the main bug, because it's actually a bug. 
microphone and play button: yea, but i think there are more serious things to be fixed. 
exact values: you mean the sliders? it usually doesn't matter if you choose 3.964 or 4.0 for some value. if you want to reset to the default, click on the number next to the slider.

**Comment by Juesto** [comment]
well, some minor issues do not deserve an additional report. no problem? yes those are mostly cosmetic and they can wait but at least its reported now... this bug along with the ui not hiding issue apparently were never reported here but mentioned on other places.

using the slider causes a very specific value written in settings. (i discovered the reset default thing myself but thanks anyway, i dont completely like the defaults through, the issue is when i want a specific non-default value, nevermind since i already worked around that by closing the app and editing settings.txt directly.)

Thank you for the attention.

**Comment by Juesto** [comment]
i notice this issue most often when there's either a complex sound drawing (likely a drop i am not sure) or when it's not WAV.
See #24.

**Comment by kritzikratzi** [comment]
"Play time randomly flickering" is fixed, will come with 1.0.8
