### ISSUE TITLE
make: *** No rule to make target '../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.

### ISSUE THREAD

**Issue by Suhmedoh** [kritzikratzi/Oscilloscope#45]
I'm having trouble installing this on Ubuntu 16.04.

I've cloned the addons into their folders, prepare.sh runs fine, but trying to run `make` gives the following error:

```
Makefile:20: ../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk: No such file or directory


make: *** No rule to make target '../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk'.  Stop.
```

Any idea how to fix this?

**Comment by kritzikratzi** [comment]
hey! 


oh, this might be a pain. haven't made a linux version in a long time. 
are you using OF0.9.3?

**Comment by Suhmedoh** [comment]
I installed latest OF (0.9.8?) and followed the instructions here: http://openframeworks.cc/setup/linux-install/

just not sure how openFrameworks works, never used it before.  I believe it's installed correctly, it runs the polygon example just fine... I feel like I must be missing something somewhere...

**Comment by kritzikratzi** [comment]
yea, the linux version is very dated. probably hasn't been compiled for linux since OF0.8

you should grab of0.9.3., that's what the oscilloscope is currently written for. then take the makefiles from the emptyExample, drop them in the oscillscope folder and try again. (leave the addon_config file as is!)

**Comment by kritzikratzi** [comment]
ps. ooh, i just realize you'll have to do more than that, because the `ofxAvCodec` also hasn't been updated for linux in a long time. 

so before you start, switch the submodule to this clone: https://github.com/pierrep/ofxAvCodec
it'll be merged soon because apparently there's a bit of interest in linux again. https://github.com/kritzikratzi/ofxAvCodec/pull/9

**Comment by kritzikratzi** [comment]
closing this in favor of https://github.com/kritzikratzi/Oscilloscope/issues/47
