### ISSUE TITLE
support 3channel wavs

### ISSUE THREAD

**Issue by kritzikratzi** [kritzikratzi/Oscilloscope#46]
support for 3channel wavs woul be very nice. 

necessary changes: 

* update the resampling pipeline (3rd channel must be available, but discarded before playback) 
* add an option to enable/disable z-modulation when there are three channels
* update the shader accordingly

**Comment by macumbista** [comment]
Hi Hansi, I'll go ahead and comment here. In a typical oscilloscope, Z modulation controls the brightness of the beam. It is a unipolar signal in the positive domain only (although I don't see why the digital version couldn't simply wrap everything in a bipolar signal around into positive brightness values again). I would love to see support for this for a live audio input stream, so that it could be better integrated with my Vector Synthesis project. Thanks!

**Comment by kritzikratzi** [comment]
imho -1..0 mean a reduction in brightness and 0...1 a boost in brightness seems intuitive give how digital audio works.

**Comment by macumbista** [comment]
Yes that makes sense!

**Comment by macumbista** [comment]
I guess that would sum with whatever value the GUI has set for the brightness?

**Comment by kritzikratzi** [comment]
i'm _guessing_ a multiplication with a^z with some fixed a, but not sure. 
should be easy enough to derive the actual equation by taking a few pictures of the effect on a scope.

**Comment by kritzikratzi** [comment]
i went for 0...1, making it darker (as i said earlier) actually makes no sense, because it's already invisible at 0 :) 

for now i'm clipping that range (ie less or equal zero is invisible). 
liveinput has no channel selector, so for now this works with file input only. 

sending you a binary in a bit.

**Comment by kritzikratzi** [comment]
clsoing this because ... it's already in the master branch and seems to work (just not publicly released yet, but that's another story).
