### ISSUE TITLE
 fatal error: ofxMightyUI.h: No such file or directory

### ISSUE THREAD

**Issue by litethink** [kritzikratzi/Oscilloscope#85]
when make -j2

**Comment by kritzikratzi** [comment]
sounds like you didn't pull the submodules. this file should definitely be there :) 

if you're building on linux you also want to do a pull from master for ofxNative and ofxLiblaserdock instead of the revisions currently linked (also see the discussion here https://github.com/kritzikratzi/Oscilloscope/pull/84 )
